version: '3.7'
volumes: 
  db-data:
services:
    database:
        image: 'mysql:latest'
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: symfony
            MYSQL_DATABASE: symfony_docker
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
    phpmyadmin:
        depends_on: 
            - database
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: database
        